version: "3.9"

services:
    backend:
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        container_name: nftMarketPlace-backend
        image: nft_backend
        restart: always
        ports:
            - 8000:8000
    frontend:
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        container_name: nftMarketPlace-frontend
        image: nft_frontend
        restart: always
        ports:
            - 3000:3000
